### ISSUE TITLE
Assignment 5 complete

### ISSUE THREAD

**Issue by eelmstrom** [eelmstrom/Assignment-5#1]
Completed assignment 5 project/repository. Uploaded exploratory figure and an expository figure for each site. 

Mark- I'm having trouble assigning you to this issue so I added you as a collaborator? See the pic below. Hope this works. I'll follow up with an email as well. 

![image](https://user-images.githubusercontent.com/60152026/108667369-e8361000-748d-11eb-9a64-072e27282af4.png)

**Comment by mdscheuerell** [comment]
Nice figures, Liz!
